tag_dict = {
    "track_title": "\xa9nam",
    "album": "\xa9alb",
    "artist": "\xa9ART",
    "album_artist": "aART",
    "composer": "\xa9wrt",
    "year": "\xa9day",
    "comment": "\xa9cmt",
    "description (usually used in podcasts)": "desc",
    "purchase date": "purd",
    "grouping": "\xa9grp",
    "genre": "\xa9gen",
    "lyrics": "\xa9lyr",
    "podcast URL": "purl",
    "podcast episode GUID": "egid",
    "podcast category": "catg",
    "podcast keywords": "keyw",
    "encoded by": "\xa9too",
    "copyright": "cprt",
    "album sort order": "soal",
    "album artist sort order": "soaa",
    "artist sort order": "soar",
    "title sort order": "sonm",
    "composer sort order": "soco",
    "show sort order": "sosn",
    "show name": "tvsh",
    "work": "\xa9wrk",
    "movement": "\xa9mvn",
    "track_number_total_tracks": "trkn",
    "disk_number_total_disks": "disk",
}
"""
Tag keys in mutagen are not human readable. This dict maps human-readable keys to mutagen keys.
"""
